services:
  app:
    container_name: notion-blog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    tty: true
    volumes:
      - ./:/app

volumes:
  notion-blog:
